// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgzfakbddogmjxxcdflf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnemZha2JkZG9nbWp4eGNkZmxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjgxNjYsImV4cCI6MjA2NjgwNDE2Nn0.mtvLy6JOvl-xJxkegXbnHEC4R2ABNPt_QvWFALWodHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});